# Dependencies
markdown:         Kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Alap Kshirsagar
tagline:          Personal Webpage
# description:
url:              https://alapkshirsagar.github.io/
baseurl:

author:
  name:           Alap Kshirsagar
#  url:            https://twitter.com/mdo

paginate:         5
plugins:           [jekyll-paginate, jekyll-gist, jekyll-seo-tag]
# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/alapkshirsagar
