# Dependencies
markdown:         Kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
# title:            Alap
# tagline:          'A Jekyll theme'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           Alap Kshirsagar
#  url:            https://twitter.com/mdo

paginate:         5
gems:           [jekyll-paginate, jekyll-gist]
# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/alapkshirsagar
